modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/tylerr147/Resize/issues"
license="MIT"

[[mods]]
modId="resize"
version="${file.jarVersion}"
displayName="Resize"
displayURL="https://github.com/tylerr147/Resize"
logoFile="logo.png"
credits="tylerr147, Kamesuta"
authors="tylerr147"
description='''
A remake of some of the features from the Gulliver Mod.
'''
[[dependencies.resize]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.resize]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
